### ISSUE TITLE
NotSupportedException on Database First

### ISSUE THREAD

**Issue by diegomesata** [MikaelEliasson/EntityFramework.Utilities#37] opened 2015-05-05 20:35 UTC
Hello I have a Database First EF Model, can I use EntityFramework.Utilities?

I'm getting this error on bulk insert.

System.NotSupportedException: Creating a DbModelBuilder or writing the EDMX from a DbContext created using Database First or Model First is not supported. EDMX can only be obtained from a Code First DbContext created without using an existing DbCompiledModel. 
[15500]    at System.Data.Entity.Infrastructure.EdmxWriter.WriteEdmx(DbContext context, XmlWriter writer) 
[15500]    at EntityFramework.Utilities.EfMapping.GetEdmx(DbContext db) 
[15500]    at EntityFramework.Utilities.EfMapping..ctor(DbContext db) 
[15500]    at EntityFramework.Utilities.EfMappingFactory.GetMappingsForContext(DbContext context) 
[15500]    at EntityFramework.Utilities.EFBatchOperation`2.InsertAll(IEnumerable`1 items, DbConnection connection, Nullable`1 batchSize)

**Comment by diegomesata** [comment] 2015-05-05 20:43
Hello I found some information on # 27, but I dont understand, updating to EF 6.1.1 fix the error?

Thank you

**Comment by derix** [comment] 2015-05-12 14:56
I'm using 6.1.3 and having the same issue?!
Does anyone have a solution or workaround?

Im using version EFUtilities 0.5.0

**Comment by diegomesata** [comment] 2015-05-12 15:16
Hello, finally I used https://efbulkinsert.codeplex.com

**Comment by derix** [comment] 2015-05-12 15:18
Cool! I saw that as well.
But it does not nsupport optimized Update. Only Insert. 
I will give it a try. Many thanks.

**Comment by diegomesata** [comment] 2015-05-12 15:24
Hello Derix, you are right only Insert, that was my use case. It's a shame that EFUtilities doesn't work with EF6

**Comment by derix** [comment] 2015-05-12 15:25
Thanks for your prompt response :)

**Comment by MikaelEliasson** [comment] 2015-05-12 15:26
I'm trying to build a fix for this now. Have had way too much work. The fix means changing to EF 6.1 or higher as a dependency though.

**Comment by derix** [comment] 2015-05-12 15:40
Many thanks. Would be happy to use this fix once ready.

**Comment by derix** [comment] 2015-05-12 16:03
EntityFramework.BulkInsert does not support the latest EF 6.1.3 :(

**Comment by derix** [comment] 2015-05-12 16:27
Mikael Eliasson can you please tell me the secret on how to perfom fast UPDATE ? I have 50K entities that need to be updated every 10 seconds...
for the Insert I currently use SqlBulkCopy which is very fast... but I have no solution for fast UPDATE.

**Comment by blastdan** [comment] 2015-05-12 16:35
Hey derix.

You may want reconsider using Entity Framework for that kind of task. This task would best be done in the database on it's own trigger or event. Or even reconsider the logic that is forcing you to work your database so hard.

however if you want to try the example on the front page would work, but you are skipping updating your DB context. you would need to reattach each of the updated items to see the changes in your context.

using (var db = new YourDbContext())
            {
                EFBatchOperation.For(db, db.Comments)
                                              .Where(x => x.Text == "a")
                                              .Update(x => x.Reads, x => x.Reads + 1);
            }

**Comment by MikaelEliasson** [comment] 2015-05-12 16:41
@derix It depends a bit on the type of update you need to do. @blastdan showed you how you can do it with EFUtilties if it's possible to do with an update by query. 

If the update is more complex it's possible to do by doing it in two steps.

1) Insert the items to a temp table using the bulk insert.
2) Execute an sql command against the db that updates the items in your table with the contents in the temp table. Then delete all items in the temp table.

**Comment by MikaelEliasson** [comment] 2015-05-14 10:58
Duplicate of #27 closing this one

**Closed by MikaelEliasson** 2015-05-14 10:58 UTC

**Comment by MikaelEliasson** [comment] 2015-05-15 05:09
@derix and @blastdan See the new feature for doing updates from an in memory collection fast.

https://github.com/MikaelEliasson/EntityFramework.Utilities#batch-update-entities
